WebApp/Models/ErrorViewModel.cs
using System;

namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/SolicitudController.cs
using Microsoft.AspNetCore.Mvc;
using Clases;
using ModeloDb;
using System.Collections;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Operaciones;
using System.Linq;

namespace WebApp.Controllers
{
    public class SolicitudController : Controller
    {
      
        private readonly TarjetaContex db;
        public SolicitudController(TarjetaContex db)
        {
            this.db = db;

        }
        public IActionResult Index()
        {
            var listaSolicitudes = db.Solicitudes
                .Include(solicitudes => solicitudes.Usuario)
                .Include(solicitudes => solicitudes.Deuda)
                .Include(solicitudes => solicitudes.Tarjeta)
                ;
            return View(listaSolicitudes);
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(Solicitud solicitud)
        {
            return View();
        }

        //edition solicitud
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            //consultar solicitud por medio del id
            Solicitud solicitud = db.Solicitudes.Find(Id);
            return View(solicitud);
        }
        [HttpPost]
        public IActionResult Edit(Solicitud solicitud)
        {
            //consultar usuario por medio id
            db.Solicitudes.Update(solicitud);
            db.SaveChanges();
            TempData["mensaje"] = $"La Solicitud {solicitud.id} a sido editada exitosamente";
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            //consultar usuario por medio id
            Solicitud solicitud = db.Solicitudes.Find(Id);
            return View(solicitud);
        }
        [HttpPost]
        public IActionResult Delete(Solicitud solicitud)
        {
            //consultar usuario por medio id
            db.Solicitudes.Remove(solicitud);
            db.SaveChanges();
            TempData["mensaje"] = $"La solicitud {solicitud.id} a sido creado borrado exitosamente";
            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult Validar()
        {

            return View();
        }


        [HttpPost]
        public IActionResult Validar(int id)
        {
            var soli = db.Solicitudes
                 .Include(u => u.Usuario)
                 .Include(t => t.Tarjeta)
                 .Include(d => d.Deuda)
                 .Include(det => det.SolicitudDets)
                 .ThenInclude(p => p.PorcentajeEndeudamiento)
                 .Include(c => c.Registro)
                 .Single(m => m.id == id);
            //preparo clase clacular 
            var confif = db.Configuracions.Single();
            PorPor porcetaje = new PorPor(confif);
            ViewBag.Vali = porcetaje;

            return View(soli);

        }
    }
}

WebApp/Controllers/UsuarioController.cs
using Clases;
using Microsoft.AspNetCore.Mvc;
using ModeloDb;
using System.Collections;
using System.Collections.Generic;

namespace WebApp.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly TarjetaContex db;
        public UsuarioController(TarjetaContex db) {
          this.db = db;
        
        }
        public IActionResult Index()
        {
            IEnumerable <Usuario> listaUsuarios = db.Usuarios;
            return View(listaUsuarios);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create( Usuario usuario)
        {
            db.Usuarios.Add(usuario);
            db.SaveChanges();
            TempData["mensaje"] = $"El usuario {usuario.Nombre} a sido creado creado exitosamente";


            return RedirectToAction("Index");
        }
       
        //edition usuario
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            //consultar usuario por medio id
            Usuario usuario = db.Usuarios.Find(Id);
            return View(usuario);
        }
        [HttpPost]
        public IActionResult Edit(Usuario usuario)
        {
            //consultar usuario por medio id
            db.Usuarios.Update(usuario);
            db.SaveChanges();
            TempData["mensaje"] = $"El usuario {usuario.Nombre} a sido editado exitosamente";
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            //consultar usuario por medio id
            Usuario usuario = db.Usuarios.Find(Id);
            return View(usuario);
        }
        [HttpPost]
        public IActionResult Delete(Usuario usuario)
        {
            //consultar usuario por medio id
            db.Usuarios.Remove(usuario);
            db.SaveChanges();
            TempData["mensaje"] = $"El usuario {usuario.Nombre} a sido creado borrado exitosamente";
            return RedirectToAction("Index");

        }
    }
}

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    
    <img  class="img1" src=~/black.jpg width=100%>
</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aprueba Tarjeta de credito</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-danger bg-alert-danger">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Solicitud</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Solicitud" asp-action="">Solicitud</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="">Usuarios</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TarjetaController1" asp-action="">Tarjeta</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()

        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SolicitudTarjeta - <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/Views/Solicitud/Create.cshtml
@using System.Collections
@using Clases

@model Solicitud
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Matrícula</h1>

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <form method="post" asp-action="Validar">
                <div class="form-group">
                    <label class="control-label">Solicitud Id</label>
                    <input class="form-control" asp-for="id" />
                </div>
                <div class="form-group">
                    <label class="control-label">Tarjeta</label>
                    <input class="form-control" asp-for="Tarjeta.NombreTarjeta" />
                </div>
                <div class="form-group">
                    <label class="control-label">Usuario</label>
                    <input class="form-control" asp-for="Usuario.Nombre" />
                </div>
                <div class="form-group">
                    <label class="control-label">Deuda</label>
                    <input class="form-control" asp-for="Deuda.CantidadDeuda" />
                </div>
                <div class="form-group">
                    <label class="control-label">Ingresos</label>
                    <input class="form-control" asp-for="Ingresos" />
                </div>
                <div class="form-group">
                    <label class="control-label">Estado</label>
                    <input class="form-control" asp-for="SolicitudEstado" />
                </div>
                <div class="form-group">
                    <label class="control-label">Privada </label>
                    <input class="form-control" asp-for="YearsTrabajoPublica" />
                </div>
                <div class="form-group">
                    <label class="control-label">Factura </label>
                    <input class="form-control" asp-for="YearsFactura" />
                </div>
                  <div class="form-group">
                    <label class="control-label">Years Trabajo Publica </label>
                    <input class="form-control" asp-for="YearsTrabajoPublica" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Validar" class="btn btn-primary" />
                </div>
            </form>
        </div>

        <div class="col-sm-8">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr> 
                            <td>ID</td>
                            <td>TARJETA</td>
                            <td>USUARIO</td>
                            <td>DEUDA</td>
                            <td>INGRESO</td>
                            <td>PRIVADA</td>
                            <td>PUBLICA</td>
                            <td>FACTURA</td>
                            <td>Estado</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.SolicitudDets)
                        {
                            <tr>
                                <td>@item.Deuda.CantidadDeuda</td>
                                <d>@item.Solicitud.Ingresos</d>
                                <td>@item.Solicitud.YearsFactura</td>
                                <td>@item.Solicitud.YearsTrabajoPublica</td>
                                <td>@item.Solicitud.YearsFactura</td>
                                <td>@item.usuario</td>

                            @if (item.PorcentajeEndeudamiento != null) 
                            {
                                <td>@item.Deuda.CantidadDeuda</td>
                                <td>@item.Solicitud.Ingresos</td>
                                <td>@item.Solicitud.YearsFactura</td>
                                <td>@item.Solicitud.YearsTrabajoPublica</td>
                                <td>@item.Solicitud.YearsTranajoPrivado</td>
                                <td>@ViewBag.Vali.Aprobado(item)</td>
                            }
                            else
                            {
                                <td>--</td>
                                <td>--</td>
                                <td>--</td>
                                <td>--</td>
                                <td>--</td>
                            }

                            </tr>
                        }
                    </tbody>
                </table>
        </div>
    </div>



</div>

WebApp/Views/Solicitud/Index.cshtml
@using System.Collections
@using Clases
@model IEnumerable<Solicitud>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class= "colcol-sm-6">
            <h3>Lista Solicitudes</h3>
        </div>
    </div>
    @if (TempData ["mensaje"] != null){
    <div class="alert alertalert-warning alert-alert-dismissible fade show" role="alert">
        @TempData["Mensaje"]
        <button type="button" class="close" data-data-dismiss="alert" ariaaria-label="close">
            <span ariaaria-hidden="true">
                &times;
            </span>
        </button>

    </div>
    }
<div class="table table-bordered">
    <table>
        <thead>
            <tr>
              <td>Id</td>
              <td>Ingresos</td>
              <td>Nombre Empresa</td>
              <td>TipoEmpresa</td>
              <td>Nombre usuario</td>
              <td>Nombre Trajeta</td>
            </tr>
        </thead>
        <tbody>
                @foreach(Solicitud solicitud in Model)
                {
                   <tr>
                    <td>@solicitud.id</td> 
                   <td>@solicitud.Ingresos</td> 
                   <td>@solicitud.NombreEmpresa </td> 
                   <td>@solicitud.Usuario.Nombre</td> 
                   <td>@solicitud.Tarjeta.NombreTarjeta</td>
                   <td>
                       <a class="btn btn-warning"
                       asp-controller="SolicitudController" asp-action="Edit" asp-route-id="@solicitud.id"
                       >
                           
                           Editar
                       </a>
                       <a class="btn btn-danger"
                       asp-controller="Solicitud" asp-action="Delete" asp-route-id="@solicitud.id"
                       >
                           Borrar
                       </a>
                       
                        <a asp-controller="Solicitud" asp-action="Validar" asp-route-id="@solicitud.id" class="btn btn-warning">Ver</a>
                    
                   </td>
                   </tr>
                }     
        </tbody>
    </table>
      <div class="col-sm-6">
        <a class="btn btn-success d-block" 
        asp-controller = "Solicitud" asp-action="Create"
        >
            Crear nueva Solicitud
        </a>
        </div>
</div>
</div>

WebApp/Views/Solicitud/Validar.cshtml
@using System.Collections
@using Clases

@model Solicitud
@{
    ViewData["Title"] = "Validar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Matrícula</h1>

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <form method="post" asp-action="Validar">
                <div class="form-group">
                    <label class="control-label">Solicitud Id</label>
                    <input class="form-control" asp-for="id" />
                </div>
                <div class="form-group">
                    <label class="control-label">Tarjeta</label>
                    <input class="form-control" asp-for="Tarjeta.NombreTarjeta" />
                </div>
                <div class="form-group">
                    <label class="control-label">Usuario</label>
                    <input class="form-control" asp-for="Usuario.Nombre" />
                </div>
                <div class="form-group">
                    <label class="control-label">Deuda</label>
                    <input class="form-control" asp-for="Deuda.CantidadDeuda" />
                </div>
                <div class="form-group">
                    <label class="control-label">Ingresos</label>
                    <input class="form-control" asp-for="Ingresos" />
                </div>
                <div class="form-group">
                    <label class="control-label">Estado</label>
                    <input class="form-control" asp-for="SolicitudEstado" />
                </div>
                <div class="form-group">
                    <label class="control-label">Privada </label>
                    <input class="form-control" asp-for="YearsTrabajoPublica" />
                </div>
                <div class="form-group">
                    <label class="control-label">Factura </label>
                    <input class="form-control" asp-for="YearsFactura" />
                </div>
                  <div class="form-group">
                    <label class="control-label">Years Trabajo Publica </label>
                    <input class="form-control" asp-for="YearsTrabajoPublica" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Validar" class="btn btn-primary" />
                </div>
            </form>
        </div>

        <div class="col-sm-8">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr> 
                            <td>ID</td>
                            <td>TARJETA</td>
                            <td>USUARIO</td>
                            <td>DEUDA</td>
                            <td>INGRESO</td>
                            <td>PRIVADA</td>
                            <td>PUBLICA</td>
                            <td>FACTURA</td>
                            <td>Estado</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.SolicitudDets)
                        {
                            <tr>
                                <td>@item.Deuda.CantidadDeuda</td>
                                <d>@item.Solicitud.Ingresos</d>
                                <td>@item.Solicitud.YearsFactura</td>
                                <td>@item.Solicitud.YearsTrabajoPublica</td>
                                <td>@item.Solicitud.YearsFactura</td>
                                <td>@item.usuario</td>

                            @if (item.PorcentajeEndeudamiento != null) 
                            {
                                <td>@item.PorcentajeEndeudamiento.Ingresos</td>
                                <td>@item.PorcentajeEndeudamiento.DeudaMonto</td>
                                <td>@item.PorcentajeEndeudamiento.por30</td>
                                <td>@ViewBag.Vali.Aprobado(item.PorcentajeEndeudamiento)</td>
                            }
                            else
                            {
                                <td>--</td>
                                <td>--</td>
                                <td>--</td>
                                <td>--</td>
                                <td>--</td>
                            }

                            </tr>
                        }
                    </tbody>
                </table>
        </div>
    </div>



</div>

WebApp/Views/TarjetaController1/Create.cshtml
@using Clases
@model Tarjeta
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h1>Creacion Tarjeta</h1>

<div class="container">
 <div class="row">
<div class="col-sm-12">
    <h3>Nueva Tarjeta</h3>
</div>
</div>
<div class="row">
    <div class="col-sm-10">
        <form method="post" asp-action="Create">
            <div class="form-group">
                <label class="custom-control-label">Nombre Tarjeta</label>
                <input class="form-control" asp-for="NombreTarjeta"/>
            </div>
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Crear Tarjeta" />
            </div>
        </form>
</div>
</div>
</div>

WebApp/Views/TarjetaController1/Delete.cshtml
@using Clases
@model Tarjeta
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h1>Creacion Tarjeta</h1>

<div class="container">
 <div class="row">
<div class="col-sm-12">
    <h3>Nueva Tarjeta</h3>
</div>
</div>
<div class="row">
    <div class="col-sm-10">
        <form method="post" asp-action="Delete">
            <div class="form-group">
                <label class="custom-control-label">Nombre Tarjeta</label>
                <input class="form-control" asp-for="NombreTarjeta"/>
            </div>
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Borrar Tarjeta" />
            </div>
        </form>
</div>
</div>
</div>

WebApp/Views/TarjetaController1/Edit.cshtml
@using Clases
@model Tarjeta
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
 <div class="row">
<div class="col-sm-12">
    <h3>Nueva Tarjeta</h3>
</div>
</div>
<div class="row">
    <div class="col-sm-10">
        <form method="post" asp-action="Edit">
            <div class="form-group">
                <label class="custom-control-label">Nombre Tarjeta</label>
                <input class="form-control" asp-for="NombreTarjeta"/>
            </div>
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Crear Tarjeta" />
            </div>
        </form>
</div>
</div>
</div>

WebApp/Views/TarjetaController1/Index.cshtml
@using System.Collections
@using Clases
@model IEnumerable<Tarjeta>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Lista Usuarios</h1>
<p>Lista de usuraios para solicitud de tarjeta de credito</p>
<div class="container">
    <div class="row">
        <div class= "colcol-sm-6">
            <h3>Lista Usuarios</h3>
        </div>
        <div class="col-sm-6">
        <a class="btn btn-success d-block" 
        asp-controller = "TarjetaController1" asp-action="Create"
        >
            Crear nueva Tarjeta
        </a>
        </div>
    </div>
    @if (TempData ["mensaje"] != null){
    <div class="alert alertalert-warning alert-alert-dismissible fade show" role="alert">
        @TempData["Mensaje"]
        <button type="button" class="close" data-data-dismiss="alert" ariaaria-label="close">
            <span ariaaria-hidden="true">
                &times;
            </span>
        </button>

    </div>
    }
<div class="row">
    <table>
        <thead>
            <tr>
              <td>Id</td>
              <td>Nombre Tarjeta</td>
            </tr>
        </thead>
        <tbody>
                @foreach(Tarjeta tarjeta in Model)
                {
                   <tr>
                   <td>@tarjeta.NombreTarjeta</td> 
                   <td>
                       <a class="btn btn-warning"
                       asp-controller="TarjetaController1" asp-action="Edit" asp-route-id="@tarjeta.Id"
                       >
                           
                           Editar
                       </a>
                       <a class="btn btn-danger"
                       asp-controller="TarjetaController1" asp-action="Delete" asp-route-id="@tarjeta.Id"
                       >
                           Borrar
                       </a>
                   </td>
                   </tr>
                }     
        </tbody>
    </table>
</div>
</div>

WebApp/Views/Usuario/Create.cshtml
@using Clases
@model Usuario

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}
<link rel="stylesheet" href="~/css~/css/StyleSheet.css" />

<div class="container">
 <div class="row">
<div class="col-sm-12">
    <h3>Nuevo Usuario</h3>
</div>
</div>
<div class="row">
    <div class="col-sm-10">
        <form method="post" asp-action="Create">
            <div class="form-group">
                <label class="custom-control-label">Nombre</label>
                <input class="form-control" asp-for="Nombre"/>
            </div>
             <div class="form-group">
                <label class="custom-control-label">Apellido</label>
                <input class="form-control" asp-for="Apellido"/>
            </div>
             <div class="form-group">
                <label class="custom-control-label">Cedula</label>
                <input class="form-control" asp-for="Cedula"/>
            </div>
             <div class="form-group">
                <label class="custom-control-label">Correo</label>
                <input class="form-control" asp-for="Email"/>
            </div>
             <div class="form-group">
                <label class="custom-control-label">Edad</label>
                <input class="form-control" asp-for="Edad"/>
            </div>
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Crear Usuario" />
            </div>
        </form>
</div>
</div>
</div>

WebApp/Views/Usuario/Delete.cshtml
@using Clases
@model Usuario

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Borrar Usuario</h1>
<div class="container">
 <div class="row">
<div class="col-sm-12">
</div>
</div>
<div class="row">
    <div class="col-sm-10">
        <form method="post" asp-action="Delete">
            <div class="form-group">
                <label class="custom-control-label">Nombre</label>
                <input class="form-control" asp-for="Nombre" disabled/>
            </div>
             <div class="form-group">
                <label class="custom-control-label">Apellido</label>
                <input class="form-control" asp-for="Apellido" disabled/>
            </div>
             <div class="form-group">
                <label class="custom-control-label">Cedula</label>
                <input class="form-control" asp-for="Cedula" disabled/>
            </div>
             <div class="form-group">
                <label class="custom-control-label">Correo</label>
                <input class="form-control" asp-for="Email" disabled/>
            </div>
             <div class="form-group">
                <label class="custom-control-label">Edad</label>
                <input class="form-control" asp-for="Edad" disabled/>
            </div>
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Confirmar borrado de Usuario" />
            </div>
        </form>
</div>
</div>

</div>

WebApp/Views/Usuario/Edit.cshtml
@using Clases
@model Usuario

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Editar Usuario</h1>
<div class="container">
 <div class="row">
<div class="col-sm-12">
</div>
</div>
<div class="row">
    <div class="col-sm-10">
        <form method="post" asp-action="Edit">
            <div class="form-group">
                <label class="custom-control-label">Nombre</label>
                <input class="form-control" asp-for="Nombre"/>
            </div>
             <div class="form-group">
                <label class="custom-control-label">Apellido</label>
                <input class="form-control" asp-for="Apellido"/>
            </div>
             <div class="form-group">
                <label class="custom-control-label">Cedula</label>
                <input class="form-control" asp-for="Cedula"/>
            </div>
             <div class="form-group">
                <label class="custom-control-label">Correo</label>
                <input class="form-control" asp-for="Email"/>
            </div>
             <div class="form-group">
                <label class="custom-control-label">Edad</label>
                <input class="form-control" asp-for="Edad"/>
            </div>
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Actualizar Usuario" />
            </div>
        </form>
</div>
</div>

</div>

WebApp/Views/Usuario/Index.cshtml
@using System.Collections
@using Clases
@model IEnumerable<Usuario>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class= "colcol-sm-6" >
            <h3 class="align-content-center">Lista Usuarios</h3>
        </div>
    </div>
    @if (TempData ["mensaje"] != null){
    <div class="alert alertalert-warning alert-alert-dismissible fade show" role="alert">
        @TempData["Mensaje"]
        <button type="button" class="close" data-data-dismiss="alert" ariaaria-label="close">
            <span ariaaria-hidden="true">
                &times;
            </span>
        </button>

    </div>
    }
<div class="table table-bordered ">
    <table>
        <thead>
            <tr>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>Cedula</th>
              <th>Edad</th>
              <th>Email</th>
            </tr>
        </thead>
        <tbody>
                @foreach(Usuario usuario in Model)
                {
                   <tr>
                   <td>@usuario.Nombre</td> 
                   <td>@usuario.Apellido</td> 
                   <td>@usuario.Cedula</td> 
                   <td>@usuario.Edad</td> 
                   <td>@usuario.Email </td> 
                   <td class="border">
                       <a class="btn btn-warning"
                       asp-controller="Usuario" asp-action="Edit" asp-route-id="@usuario.Id"
                       >
                           
                           Editar
                       </a>
                       <a class="btn btn-danger"
                       asp-controller="Usuario" asp-action="Delete" asp-route-id="@usuario.Id"
                       >
                           Borrar
                       </a>
                   </td>
                   </tr>
                }     
        </tbody>
    </table>
    <div class="col-sm-6">
        <a class="btn btn-success d-block" 
        asp-controller = "Usuario" asp-action="Create"
        >
            Crear nuevo Usuario
        </a>
        </div>
</div>
</div>